[tool.poetry]
name = "recognize-handwritten-letters"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.26.1"
pandas = "^2.1.1"
matplotlib = "^3.8.0"
scikit-learn = "^1.3.2"
seaborn = "^0.13.0"
jupyter = "^1.0.0"
keras = "^2.12.0"
tensorflow = "^2.12.0"
tensorflow-io-gcs-filesystem = "^0.31.0"

[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^23.10.1"}
isort = "^5.12.0"
nbqa = "^1.7.1"
poethepoet = "^0.24.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
